export const drivers = [
  {
    id: "1",
    firstName: "Alexander",
    lastName: "Albon",
    flag: "088-thailand.svg",
    number: "23",
    color: "#37BEDD",
  },
  {
    id: "2",
    firstName: "Fernando",
    lastName: "Alonso",
    flag: "230-spain.svg",
    number: "14",
    color: "#358C75",
  },
  {
    id: "3",
    firstName: "Valtteri",
    lastName: "Bottas",
    flag: "211-finland.svg",
    number: "77",
    color: "#00E701",
  },
  {
    id: "4",
    firstName: "Pierre",
    lastName: "Gasly",
    flag: "197-france.svg",
    number: "10",
    color: "#2293D1",
  },
  {
    id: "5",
    firstName: "Lewis",
    lastName: "Hamilton",
    flag: "110-united kingdom.svg",
    number: "44",
    color: "#6CD3BF",
  },
  {
    id: "6",
    firstName: "Nico",
    lastName: "Hulkenberg",
    flag: "208-germany.svg",
    number: "27",
    color: "#B6BABD",
  },
  {
    id: "7",
    firstName: "Charles",
    lastName: "Leclerc",
    flag: "220-monaco.svg",
    number: "16",
    color: "#F91536",
  },
  {
    id: "8",
    firstName: "Kevin",
    lastName: "Magnussen",
    flag: "191-denmark.svg",
    number: "20",
    color: "#B6BABD",
  },
  {
    id: "9",
    firstName: "Lando",
    lastName: "Norris",
    flag: "110-united kingdom.svg",
    number: "4",
    color: "#F58020",
  },
  {
    id: "10",
    firstName: "Esteban",
    lastName: "Ocon",
    flag: "197-france.svg",
    number: "31",
    color: "#2293D1",
  },
  {
    id: "11",
    firstName: "Sergio",
    lastName: "Perez",
    flag: "033-mexico.svg",
    number: "11",
    color: "#3671C6",
  },
  {
    id: "12",
    firstName: "Oscar",
    lastName: "Piastri",
    flag: "143-australia.svg",
    number: "81",
    color: "#F58020",
  },
  {
    id: "13",
    firstName: "Daniel",
    lastName: "Ricciardo",
    flag: "143-australia.svg",
    number: "3",
    color: "#5E8FAA",
  },
  {
    id: "14",
    firstName: "George",
    lastName: "Russell",
    flag: "110-united kingdom.svg",
    number: "63",
    color: "#6CD3BF",
  },
  {
    id: "15",
    firstName: "Carlos",
    lastName: "Sainz",
    flag: "230-spain.svg",
    number: "55",
    color: "#F91536",
  },
  {
    id: "16",
    firstName: "Logan",
    lastName: "Sargeant",
    flag: "186-united states.svg",
    number: "2",
    color: "#37BEDD",
  },
  {
    id: "17",
    firstName: "Lance",
    lastName: "Stroll",
    flag: "066-canada.svg",
    number: "18",
    color: "#358C75",
  },
  {
    id: "18",
    firstName: "Yuki",
    lastName: "Tsunoda",
    flag: "241-japan.svg",
    number: "22",
    color: "#5E8FAA",
  },
  {
    id: "19",
    firstName: "Max",
    lastName: "Verstappen",
    flag: "077-netherlands.svg",
    number: "1",
    color: "#3671C6",
  },
  {
    id: "20",
    firstName: "Guanyu",
    lastName: "Zhou",
    flag: "011-china.svg",
    number: "24",
    color: "00E701",
  },
];

export const teams = [
  "Alpine",
  "Aston Martin",
  "Ferrari",
  "Haas",
  "Kick Sauber",
  "McLaren",
  "Mercedes",
  "RB",
  "Red Bull",
  "Williams",
];

export const accordionItems = [
  {
    id: 1,
    flag_img_src: "./Tracks/Bahrain/bh.svg",
    background_image: "./Tracks/Bahrain/BahrainSunset.jpeg",
    card_title_img_src: "./Countries/Bahrain.png",
    track_img_src: "./Tracks/2024.avif",
    date: "March 2",
    track_name_img_src: "./TrackNames/GULF AIR BAHRAIN GRA.png",
  },
  {
    id: 2,
    flag_img_src: "./Tracks/Saudi Arabia/sa.svg",
    background_image: "./Tracks/Saudi Arabia/SaudiArabiaNight.jpeg",
    card_title_img_src: "./Countries/Saudi Arabia.png",
    track_img_src: "./Tracks/2024.avif",
    date: "March 9",
    track_name_img_src: "./TrackNames/STC SAUDI ARABIAN GR.png",
  },
  {
    id: 3,
    flag_img_src: "./Tracks/Australia/au.svg",
    background_image: "./Tracks/Australia/MelbourneTrack.jpeg",
    card_title_img_src: "./Countries/Australia.png",
    track_img_src: "./Tracks/2024.avif",
    date: "March 24",
    track_name_img_src: "./TrackNames/ROLEX AUSTRALIAN GRA.png",
  },
  {
    id: 4,
    flag_img_src: "./Tracks/Japan/jp.svg",
    background_image: "./Tracks/Japan/JapanTrackTurn.avif",
    card_title_img_src: "./Countries/Japan.png",
    track_img_src: "./Tracks/2024.avif",
    date: "April 7",
    track_name_img_src: "./TrackNames/MSC CRUISES JAPANESE.png",
  },
  {
    id: 5,
    flag_img_src: "./Tracks/China/cn.svg",
    background_image: "./Tracks/China/ChinaFullTrack.jpeg",
    card_title_img_src: "./Countries/China.png",
    track_img_src: "./Tracks/2024.avif",
    date: "April 21",
    track_name_img_src: "./TrackNames/LENOVO CHINESE GRAND.png",
  },
  {
    id: 6,
    flag_img_src: "./Tracks/United States/us.svg",
    background_image: "./Tracks/United States/Miami/MiamiSkyView.jpeg",
    card_title_img_src: "./Countries/United States.png",
    track_img_src: "./Tracks/2024.avif",
    date: "May 5",
    track_name_img_src: "./TrackNames/CRYPTO.COM MIAMI GRA.png",
  },
  {
    id: 7,
    flag_img_src: "./Tracks/Italy/it.svg",
    background_image: "./Tracks/Italy/Imola/ImolaTurn.jpeg",
    card_title_img_src: "./Countries/Italy.png",
    track_img_src: "./Tracks/2024.avif",
    date: "May 19",
    track_name_img_src: "./TrackNames/MSC CRUISES GRAN PRE 2.png",
  },
  {
    id: 8,
    flag_img_src: "./Tracks/Monaco/mc.svg",
    background_image: "./Tracks/Monaco/MonacoTurnClose.avif",
    card_title_img_src: "./Countries/Monaco.png",
    track_img_src: "./Tracks/2024.avif",
    date: "May 26",
    track_name_img_src: "./TrackNames/GRAND PRIX DE MONACO.png",
  },
  {
    id: 9,
    flag_img_src: "./Tracks/Canada/ca.svg",
    background_image: "./Tracks/Canada/MontrealWideView.jpeg",
    card_title_img_src: "./Countries/Canada.png",
    track_img_src: "./Tracks/2024.avif",
    date: "June 9",
    track_name_img_src: "./TrackNames/AWS GRAND PRIX DU CA.png",
  },
  {
    id: 10,
    flag_img_src: "./Tracks/Spain/es.svg",
    background_image: "./Tracks/Spain/SpainTrack.avif",
    card_title_img_src: "./Countries/Spain.png",
    track_img_src: "./Tracks/2024.avif",
    date: "June 23",
    track_name_img_src: "./TrackNames/ARAMCO GRAN PREMIO D.png",
  },
  {
    id: 11,
    flag_img_src: "./Tracks/Austria/at.svg",
    background_image: "./Tracks/Austria/AustriaSkyView.avif",
    card_title_img_src: "./Countries/Austria.png",
    track_img_src: "./Tracks/2024.avif",
    date: "June 30",
    track_name_img_src: "./TrackNames/QATAR AIRWAYS AUSTRI.png",
  },
  {
    id: 12,
    flag_img_src: "./Tracks/Great Britian/gb.svg",
    background_image: "./Tracks/Great Britian/GreatBritian.jpg",
    card_title_img_src: "./Countries/Great Britian.png",
    track_img_src: "./Tracks/2024.avif",
    date: "July 7",
    track_name_img_src: "./TrackNames/QATAR AIRWAYS BRITIS.png",
  },
  {
    id: 13,
    flag_img_src: "./Tracks/Hungary/hu.svg",
    background_image: "./Tracks/Hungary/HungaryRace.avif",
    card_title_img_src: "./Countries/Hungary.png",
    track_img_src: "./Tracks/2024.avif",
    date: "July 21",
    track_name_img_src: "./TrackNames/HUNGARIAN GRAND PRIX.png",
  },
  {
    id: 14,
    flag_img_src: "./Tracks/Belgium/be.svg",
    background_image: "./Tracks/Belgium/BelgiumRacing.avif",
    card_title_img_src: "./Countries/Beligium.png",
    track_img_src: "./Tracks/2024.avif",
    date: "July 28",
    track_name_img_src: "./TrackNames/ROLEX BELGIAN GRAND.png",
  },
  {
    id: 15,
    flag_img_src: "./Tracks/Netherlands/nl.svg",
    background_image: "./Tracks/Netherlands/NetherlandsRacing.jpeg",
    card_title_img_src: "./Countries/Netherlands.png",
    track_img_src: "./Tracks/2024.avif",
    date: "August 25",
    track_name_img_src: "./TrackNames/HEINEKEN DUTCH GRAND.png",
  },
  {
    id: 16,
    flag_img_src: "./Tracks/Italy/it.svg",
    background_image: "./Tracks/Italy/Monza/MonzaPaddock.jpeg",
    card_title_img_src: "./Countries/Italy.png",
    track_img_src: "./Tracks/2024.avif",
    date: "September 1",
    track_name_img_src: "./TrackNames/PIRELLI GRAN PREMIO.png",
  },
  {
    id: 17,
    flag_img_src: "./Tracks/Azerbaijan/az.svg",
    background_image: "./Tracks/Azerbaijan/BakuCastle.avif",
    card_title_img_src: "./Countries/Azerbaijan.png",
    track_img_src: "./Tracks/2024.avif",
    date: "September 15",
    track_name_img_src: "./TrackNames/QATAR AIRWAYS AZERBA.png",
  },
  {
    id: 18,
    flag_img_src: "./Tracks/Singapore/sg.svg",
    background_image: "./Tracks/Singapore/SingaporeRacing.avif",
    card_title_img_src: "./Countries/Singapore.png",
    track_img_src: "./Tracks/2024.avif",
    date: "September 22",
    track_name_img_src: "./TrackNames/SINGAPORE AIRLINES S.png",
  },
  {
    id: 19,
    flag_img_src: "./Tracks/United States/us.svg",
    background_image: "./Tracks/United States/Austin/AustinSkyView.jpeg",
    card_title_img_src: "./Countries/United States.png",
    track_img_src: "./Tracks/2024.avif",
    date: "October 20",
    track_name_img_src: "./TrackNames/PIRELLI UNITED STATE.png",
  },
  {
    id: 20,
    flag_img_src: "./Tracks/Mexico/mx.svg",
    background_image: "./Tracks/Mexico/MexicoSkyView.jpeg",
    card_title_img_src: "./Countries/Mexico.png",
    track_img_src: "./Tracks/2024.avif",
    date: "October 27",
    track_name_img_src: "./TrackNames/GRAN PREMIO DE LA CI.png",
  },
  {
    id: 21,
    flag_img_src: "./Tracks/Brazil/br.svg",
    background_image: "./Tracks/Brazil/BrazilRacer.jpeg",
    card_title_img_src: "./Countries/Brazil.png",
    track_img_src: "./Tracks/2024.avif",
    date: "November 3",
    track_name_img_src: "./TrackNames/LENOVO GRANDE PRÊMIO.png",
  },
  {
    id: 22,
    flag_img_src: "./Tracks/United States/us.svg",
    background_image: "./Tracks/United States/Vegas/VegasRacer.jpeg",
    card_title_img_src: "./Countries/United States.png",
    track_img_src: "./Tracks/2024.avif",
    date: "November 23",
    track_name_img_src: "./TrackNames/HEINEKEN SILVER LAS.png",
  },
  {
    id: 23,
    flag_img_src: "./Tracks/Qatar/qa.svg",
    background_image: "./Tracks/Qatar/QatarSkyView.jpeg",
    card_title_img_src: "./Countries/Qatar.png",
    track_img_src: "./Tracks/2024.avif",
    date: "December 1",
    track_name_img_src: "./TrackNames/QATAR AIRWAYS QATAR.png",
  },
  {
    id: 24,
    flag_img_src: "./Tracks/Abu Dhabi/ae.svg",
    background_image: "./Tracks/Abu Dhabi/AbuDhabiSkyView.jpeg",
    card_title_img_src: "./Countries/Abu Dhabi.png",
    track_img_src: "./Tracks/2024.avif",
    date: "December 1",
    track_name_img_src: "./TrackNames/ETIHAD AIRWAYS ABU D.png",
  },
];
